page 80007 "Serv. App. Schd.- Approved"
{
    Caption = 'Serv. App. Schd.-Approved List';
    /* CardPageID = "Service App Schedule";
    DataCaptionFields = "Service Item","Service Code (KM)";
    PageType = List;
    SourceTable = Table50070;
    SourceTableView = WHERE(Appointment Status=FILTER(Approved)); */

    /* layout
    {
        area(content)
        {
            repeater(Control1000000088)
            {
                ShowCaption = false;
                field("User Date";"User Date")
                {
                }
                field(MONTH;MONTH)
                {
                    Editable = false;
                }
                field("Service App Generated By";"Service App Generated By")
                {
                }
                field("Job No.";"Job No.")
                {
                }
                field("Date Of Serv.";"Date Of Serv.")
                {
                }
                field("JOb No Updated";"JOb No Updated")
                {
                }
                field(Operation;Operation)
                {
                }
                field("Base Location";"Base Location")
                {
                }
                field("Job Type Code";"Job Type Code")
                {
                }
                field("Buisness Type";"Buisness Type")
                {
                }
                field("Shortcut dimension 3";"Shortcut dimension 3")
                {
                }
                field("Officer In Charge";"Officer In Charge")
                {
                }
                field("Service Due Kilometer";"Service Due Kilometer")
                {
                }
                field("Service Item";"Service Item")
                {
                }
                field("Last/ Current Od Reading (KM)";"Last/ Current Od Reading (KM)")
                {
                    BlankZero = true;
                    Style = Strong;
                    StyleExpr = TRUE;
                }
                field("Service Code (KM)";"Service Code (KM)")
                {
                }
                field("Service Due Projected Date";"Service Due Projected Date")
                {
                }
                field("Next Call Date.";"Next Call Date.")
                {
                }
                field("Send Appointment Reminder";"Send Appointment Reminder")
                {
                }
                field(Serviced;Serviced)
                {
                }
                field("Serviced Kilometer";"Serviced Kilometer")
                {
                }
                field("Fixed Asset No.";"Fixed Asset No.")
                {
                }
                field(Description;Description)
                {
                }
                field("Service Date";"Service Date")
                {
                }
                field("Fleet Manager";"Fleet Manager")
                {
                }
                field("Fleet Manager Name";"Fleet Manager Name")
                {
                }
                field("Fleet Manager No.";"Fleet Manager No.")
                {
                }
                field("Fleet Manager Email";"Fleet Manager Email")
                {
                }
                field("Cust. Veh. Reg Form No.";"Cust. Veh. Reg Form No.")
                {
                }
                field("Appointment Status";"Appointment Status")
                {
                }
                field("Reception Date";"Reception Date")
                {
                }
                field(Remark;Remark)
                {
                }
                field("E-Mail";"E-Mail")
                {
                }
                field("Contact Person";"Contact Person")
                {
                }
                field("Phone No 1.";"Phone No 1.")
                {
                }
                field("Phone No. 2.";"Phone No. 2.")
                {
                }
                field("Phone No. 3 (GSM).";"Phone No. 3 (GSM).")
                {
                }
                field("Customer No.";"Customer No.")
                {
                }
                field("Customer Job Type";"Customer Job Type")
                {
                }
                field("Engine No.";"Engine No.")
                {
                }
                field("Chasis No.";"Chasis No.")
                {
                }
                field("Model Code";"Model Code")
                {
                }
                field("Contact E-Mail";"Contact E-Mail")
                {
                }
                field("Response Action";"Response Action")
                {
                }
                field("Call Type";"Call Type")
                {
                }
                field("Cust. Veh. Reg Form Date";"Cust. Veh. Reg Form Date")
                {
                }
                field("Walk-In";"Walk-In")
                {
                }
            }
        }
    } */

    actions
    {
        area(navigation)
        {
            group("&Line")
            {
                Caption = '&Line';
                action(Card)
                {
                    Caption = 'Card';
                    Image = EditLines;
                    ShortCutKey = 'Shift+F7';
                    ApplicationArea =all;

                    trigger OnAction()
                    begin
                        /*CASE "Document Type" OF
                          "Document Type"::Quote:
                            PAGE.RUN(PAGE::"Sales Quote",Rec);
                          "Document Type"::Order:
                            PAGE.RUN(PAGE::"Purch. Stock Quote Subform",Rec);
                          "Document Type"::Invoice:
                            PAGE.RUN(PAGE::"Sales Invoice",Rec);
                          "Document Type"::"Return Order":
                            PAGE.RUN(PAGE::"Sales Return Order",Rec);
                          "Document Type"::"Credit Memo":
                            PAGE.RUN(PAGE::"Sales Credit Memo",Rec);
                          "Document Type"::"Blanket Order":
                            PAGE.RUN(PAGE::"Blanket Sales Order",Rec);
                        END;
                         */

                    end;
                }
            }
        }
    }

    trigger OnOpenPage()
    begin
        // SETFILTER(TODAY,FORMAT("Service Due Projected Date"));
    end;
}

